---
dist: trusty
sudo: required
services:
- docker
git:
  depth: 1
before_install:
- openssl aes-256-cbc -K $encrypted_3761ed62f3dc_key -iv $encrypted_3761ed62f3dc_iv -in key.rsa.enc -out key.rsa -d
install:
- sudo apt-get install s3cmd
notifications:
  email:
    on_success: never
    on_failure: always
script:
- find * -type d -depth 0 | xargs chmod -R 777
- make builder all push
