---
dist: trusty
sudo: required
services:
- docker
git:
  depth: 1
install:
- sudo apt-get install s3cmd
notifications:
  email:
    on_success: never
    on_failure: always
script:
- chmod -R 777 *
- find * -ls
- make builder all push
