#!/bin/sh
set -e

LC_ALL=C

function usage() {
    echo "usage: $(basename $0) list" >&2
    echo "       $(basename $0) [start|show|ssh|reset|stop|monitor] NAME" >&2
}

function parse_name() {
    NAME="$1"
    MAC="$(echo ${NAME} | cut -d'!' -f1)"
    TAP_DEVICE="cloud@$(echo ${NAME} | sha1sum | cut -c 1-9)"
    SERIAL="$(echo ${NAME} | cut -d'!' -f2)"
    MONITOR_SOCKET="/var/run/${NAME}.socket"
}

function get_ip() {
    arp -i cloud -n | grep -i "${MAC}" | sed -n -e 's/^[^\(]*(\([0-9.]*\)).*$/\1/p'
}

case "$1" in
    start)
        test -z "$2" && usage && exit 1
        parse_name "$2"
        qemu-system-x86_64 \
            -enable-kvm \
            -name "${NAME}" \
            -m "size=4G" \
            -boot "order=nc" \
            -drive "file=/srv/cloud/images/testdisk01,format=raw,if=virtio" \
            -drive "file=/srv/cloud/images/testdisk02,format=raw,if=virtio" \
            -netdev "tap,id=net0,ifname=${TAP_DEVICE},script=/usr/share/cloudctl/cloud-ifup,downscript=/usr/share/cloudctl/cloud-ifdown" \
            -device "virtio-net-pci,netdev=net0,mac=${MAC}" \
            -smbios "type=1,serial=${SERIAL}" \
            -monitor "unix:${MONITOR_SOCKET},server,nowait" \
            -vnc ":0,password" \
            -daemonize
        echo "set_password vnc ${NAME}" | nc -N -U "${MONITOR_SOCKET}"
        echo "vnc://playground.casadirocco.nl:5900 with ${NAME}"
        ;;

    list)
        find /var/run/ -name '*.socket' | sed -e 's#/var/run/##' -e 's#\.socket$##'
        ;;

    show)
        test -z "$2" && usage && exit 1
        parse_name "$2"
        if [ ! -S "${MONITOR_SOCKET}" ]; then
            echo "No machine running with name ${NAME}"
            exit 1
        fi

        echo "Name: ${NAME}"
        echo "Mac: ${MAC}"
        echo "Serial: ${SERIAL}"
        echo "Ip: $(get_ip)"
        echo "Tap: ${TAP_DEVICE}"

        ;;

    ssh)
        test -z "$2" && usage && exit 1
        parse_name "$2"
        ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $(get_ip)
        ;;

    reset)
        test -z "$2" && usage && exit 1
        parse_name "$2"
        if [ ! -S "${MONITOR_SOCKET}" ]
        then
            echo "No machine running with name ${NAME}"
            exit 1
        fi
        echo "system_reset" | nc -N -U "${MONITOR_SOCKET}"
        ;;

    stop)
        test -z "$2" && usage && exit 1
        parse_name "$2"
        if [ ! -S "${MONITOR_SOCKET}" ]
        then
            echo "No machine running with name ${NAME}"
            exit 1
        fi
        echo "quit" | nc -N -U "${MONITOR_SOCKET}"
        ;;

    monitor)
        test -z "$2" && usage && exit 1
        parse_name "$2"
        if [ ! -S "${MONITOR_SOCKET}" ]
        then
            echo "No machine running with name ${NAME}"
            exit 1
        fi
        nc -N -U "${MONITOR_SOCKET}"
        ;;

    *)
        usage && exit 1
        ;;
esac
