#!/bin/sh

if ! ip link show cloud > /dev/null
then
    ip link add cloud type bridge
    ip link set cloud up
    ip addr add 192.168.2.1/24 broadcast + dev cloud
fi

iptables -C FORWARD -i cloud -o eth0 -j ACCEPT || \
    iptables -A FORWARD -i cloud -o eth0 -j ACCEPT

iptables -C FORWARD -i eth0 -o cloud -m state --state ESTABLISHED,RELATED -j ACCEPT || \
    iptables -A FORWARD -i eth0 -o cloud -m state --state ESTABLISHED,RELATED -j ACCEPT

iptables -t nat -C POSTROUTING -s 192.168.2.0/24 -o eth0 -j MASQUERADE || \
    iptables -t nat -A POSTROUTING -s 192.168.2.0/24 -o eth0 -j MASQUERADE

ip tuntap add dev "${1}" mode tap
ip link set "${1}" master cloud
ip link set "${1}" up
